services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: mydb_test
    ports:
      - "5433:5432"  # seulement pour ta machine locale
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:test_password@postgres:5432/mydb_test
      NODE_ENV: test
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "npm install &&
             npx prisma migrate deploy &&
             npm test"
