version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: glace 123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    env_file:
      - .env

    command: sh -c "npx prisma migrate deploy && npm run start"

volumes:
  pgdata:
