apiVersion: apps/v1
kind: Deployment
metadata:
  name: pmsp-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pmsp-app
  template:
    metadata:
      labels:
        app: pmsp-app
    spec:
      containers:
        - name: pmsp-app
          image: w4jih/pmsp-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: pmsp-app-secret
                  key: DATABASE_URL
