apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=          # base64 for "postgres"
  POSTGRES_PASSWORD: Z2xhY2UgMTIz      # base64 for "glace 123"
  POSTGRES_DB: bXlkYg==                # base64 for "mydb"
