apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames: ["psmp"]
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: http
      path: /api/metrics
      interval: 15s
