apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: psmp
spec:
  replicas: 1
  selector:
    matchLabels: { app: backend }
  template:
    metadata:
      labels: { app: backend }
    spec:
      # Run Prisma migrations before the app starts
      initContainers:
        - name: prisma-migrate
          image: psmp-backend:latest
          command: ["sh", "-c", "npx prisma migrate deploy"]
          envFrom:
            - secretRef:
                name: backend-secrets
      containers:
        - name: backend
          image: psmp-backend:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: backend-secrets
          readinessProbe:
            httpGet: { path: "/", port: 3000 }
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: "/", port: 3000 }
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: psmp
spec:
  selector:
    app: backend
  type: NodePort          # For Minikube/dev
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
